spring:
  application:
    name: ms-gestion-instructor
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
         max-attempts: 20
         max-interval: 15000
         initial-interval: 10000
               
#spring:
#  application:
#      name: ms-gestion-instructor
#  config:
#    import: optional:configserver:http://localhost:8088
             
#server:
#  port: 8084
#  servlet:
#    context-path: /ms-instructor
    
#  error:
#    include-details: always
    
# Oracle settings
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: MS012021
#    password: 123456
#    driver-class-name: oracle.jdbc.driver.OracleDriver